### ISSUE TITLE
In some cases we want to ignore certificates

### ISSUE THREAD

**Issue by bassosimone** [ooni/netx#127]
@hellais mentioned to me yesterday that, for example in Malaysia, you may be redirected via DNS to a blockpage-serving website that does not have the correct certificate installed.

**Comment by hellais** [comment]
This is the issue I was thinking of https://github.com/ooni/backend/issues/684.

Looking back at it I see that this is in fact a slightly different situation as the blockpage server doesn't actually have a HTTPS server running.

I am still pretty sure we have seen this in OONI data in the past. Perhaps some more digging into the fingerprintdb issues on ooni-pipeline could yield some good results: https://github.com/ooni/pipeline/issues?q=is%3Aopen+is%3Aissue+label%3Afingerprintdb

**Comment by bassosimone** [comment]
Added this as an interrupt. It's functional to https://github.com/ooni/probe-engine/issues/2.
